EXERCISES = [
    {'name': 'Push-ups', 'slots': 1, 'speak': 'push_ups.mp3', 'area': ['biceps', 'triceps']},
    {'name': 'Squats', 'slots': 1, 'speak': 'squats.mp3', 'area': ['thigh', 'calf']},
    {'name': 'Leg-lifts', 'slots': 1, 'speak': 'leg_lifts.mp3', 'area': ['thigh', 'abdomen']},
    {'name': 'Lunges', 'slots': 1, 'speak': 'lunges.mp3', 'area': ['thigh', 'calf']},
    {'name': 'Plank', 'slots': 1, 'speak': 'plank.mp3', 'area': ['abdomen']},
    {'name': 'Triceps dips', 'slots': 1, 'speak': 'triceps_dips.mp3', 'area': ['triceps']},
    {'name': 'Crunches', 'slots': 1, 'speak': 'crunches.mp3', 'area': ['abdomen']},
    {'name': 'One-leg squats x2', 'slots': 2, 'speak': 'one_leg_squats.mp3', 'area': ['thigh', 'calf']},
    {'name': 'Single leg squats x2', 'speak': 'single_leg_squats.mp3', 'slots': 2, 'area': ['thigh', 'calf']},
    {'name': 'Calf raises', 'slots': 1, 'speak': 'calf_raises.mp3', 'area': ['calf']},
    {'name': 'Seated dips', 'slots': 1, 'speak': 'seated_dips.mp3', 'area': ['triceps']},
    {'name': 'Jumping jacks', 'slots': 1, 'speak': 'jumping_jacks.mp3', 'area': ['full body']},
    {'name': 'Side plank x2', 'slots': 2, 'speak': 'side_plank.mp3', 'area': ['abdomen', 'side hips', 'back hips']},
    {'name': 'Arm circles', 'slots': 1, 'speak': 'arm_circles.mp3', 'area': ['shoulders', 'biceps', 'triceps']},
]
