EXERCISES = [
    {'name': 'Push-ups', 'area': ['biceps', 'triceps']},
    {'name': 'Squats', 'area': ['thigh', 'calf']},
    {'name': 'Leg-lifts', 'area': ['thigh', 'abdomen']},
    {'name': 'Lunges', 'area': ['thigh', 'calf']},
    {'name': 'Plank', 'area': ['abdomen']},
    {'name': 'Triceps dips', 'area': ['triceps']},
    {'name': 'Crunches', 'area': ['abdomen']},
    {'name': 'One-leg squats', 'area': ['thigh', 'calf']},
    {'name': 'Single leg squats', 'area': ['thigh', 'calf']},
    {'name': 'Calf raises', 'area': ['calf']},
    {'name': 'Seated dips', 'area': ['triceps']},
    {'name': 'Jumping jacks', 'area': ['full body']},
    {'name': 'Side plank x2', 'area': ['abdomen', 'side hips', 'back hips']},
    {'name': 'Arm circles', 'area': ['shoulders', 'biceps', 'triceps']},
]